# Generated by Django 5.2.3 on 2025-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students_about/')),
                ('body', models.TextField()),
            ],
        ),
    ]
