# Generated by Django 5.2.3 on 2025-07-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InorganicChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='Inorganic_chemistry/')),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mathematics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='Mathematics/')),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='Organic_chemistry/')),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='Physical_chemistry/')),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='Physics/')),
                ('link', models.URLField(unique=True)),
            ],
        ),
    ]
