# Generated by Django 5.2.3 on 2025-07-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inorganicchemistry',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organicchemistry',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='physicalchemistry',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
