# Generated by Django 5.2.3 on 2025-07-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_inorganicchemistry_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inorganicchemistry',
            name='number',
        ),
        migrations.RemoveField(
            model_name='mathematics',
            name='number',
        ),
        migrations.RemoveField(
            model_name='organicchemistry',
            name='number',
        ),
        migrations.RemoveField(
            model_name='physicalchemistry',
            name='number',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='number',
        ),
    ]
